// Generated by png2c [(c) Oleg Vaskevich 2013]

#ifndef _lion_H_
#define _lion_H_

extern const unsigned int lion_width;
extern const unsigned int lion_height;
extern const int lion_size;
extern const unsigned char lion[];

#endif

