// Generated by png2c RGB888

#ifndef _tiger_H_
#define _tiger_H_

extern const unsigned int tiger_width;
extern const unsigned int tiger_height;
extern const int tiger_size;
extern const unsigned char tiger[];

#endif

